### ISSUE TITLE
作者是否参考了policy distill baseline的代码

### ISSUE THREAD

**Issue by Timerunning** [CSU-FulChou/RL_IoT_distillation#1]
policy distill baseline的代码，我看了一下，感觉全是bug，跑不通

**Comment by FulChou** [comment]
你好，不知道你指的是哪一步部分代码？
的确有参考 ～baseline中的 kl计算部分
目前此repo的实验还在我的服务器上运行，
由于算法还在开发阶段暂时还未写quick start

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Time ***@***.***&gt;
发送时间: 2021年10月25日 21:21
收件人: CSU-FulChou/RL_IoT_distillation ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[CSU-FulChou/RL_IoT_distillation] 作者是否参考了policy distill baseline的代码 (Issue #1)
